language: haskell

install:
  - sudo apt-get install libicu-dev
  - cabal install --only-dependencies --enable-tests --disable-optimization --ghc-options=-w

script:
  - cabal configure --enable-tests --disable-optimization && cabal build && cabal test
